CREATE TABLE `t_commission_detail` (
  `COMMISSION_ID` varchar(32) NOT NULL COMMENT '主键 生成规则:DF+yyyyMMddHHmmssSSS+3位数字随机码',
  `SERNO` varchar(40) NOT NULL COMMENT '业务流水号',
  `POLICY_NO` varchar(32) DEFAULT NULL COMMENT '保单号',
  `CUS_NAME` varchar(32) DEFAULT NULL COMMENT '客户姓名',
  `CUS_PHONE` varchar(32) DEFAULT NULL COMMENT '客户手机号',
  `USER_ID` varchar(32) DEFAULT NULL COMMENT '代理人ID',
  `USER_NAME` varchar(32) DEFAULT NULL COMMENT '代理人姓名',
  `USER_PHONE` varchar(32) DEFAULT NULL COMMENT '代理人手机号',
  `INVITER_USER_ID` varchar(32) DEFAULT NULL COMMENT '邀请人ID',
  `INVITER_USER_NAME` varchar(32) DEFAULT NULL COMMENT '邀请人姓名',
  `INVITER_USER_PHONE` varchar(32) DEFAULT NULL COMMENT '邀请人手机号',
  `CUS_MAMAGER_ID` varchar(32) DEFAULT NULL COMMENT '客户经理ID',
  `CUS_MAMAGER_NAME` varchar(32) DEFAULT NULL COMMENT '客户经理姓名',
  `DEPT_CODE` varchar(32) DEFAULT NULL COMMENT '所属分部编码',
  `DEPT_NAME` varchar(128) DEFAULT NULL COMMENT '所属分部名称',
  `LOAN_DATE` varchar(20) DEFAULT NULL COMMENT '放款时间 yyyy-MM-dd HH:mm:ss',
  `LOAN_AMOUNT` decimal(32,2) DEFAULT '0.00' COMMENT '放款金额',
  `POLICY_DATE` varchar(20) DEFAULT NULL COMMENT '出单时间 yyyy-MM-dd HH:mm:ss',
  `APPROVE_RESULT` varchar(10) DEFAULT NULL COMMENT '预审结果',
  `APPROVE_DATE` varchar(20) DEFAULT NULL COMMENT '预审时间 yyyy-MM-dd HH:mm:ss',
  `PREMIUM_AMOUNT` decimal(32,2) DEFAULT '0.00' COMMENT '保费收入',
  `PURE_PREMIUM_AMOUNT` decimal(32,2) DEFAULT '0.00' COMMENT '保费收入(不含税)',
  `APPLY_STATUS` varchar(10) DEFAULT NULL COMMENT '申请状态',
  `TOTAL_POUNDAGE` decimal(32,2) DEFAULT '0.00' COMMENT '合计手续费',
  `POUNDAGE_RATE` decimal(32,4) DEFAULT '0.0000' COMMENT '手续费所占比例',
  `AGENT_COMMISSION` decimal(32,2) DEFAULT '0.00' COMMENT '代理人佣金',
  `COMMISSION_RATE` decimal(32,4) DEFAULT '0.0000' COMMENT '佣金所占比例',
  `SETTLE_COMMISSION` decimal(32,2) DEFAULT '0.00' COMMENT '已结算佣金',
  `INVITER_AWARD` decimal(32,2) DEFAULT '0.00' COMMENT '邀请人奖励',
  `AWARD_RATE` decimal(32,4) DEFAULT '0.0000' COMMENT '奖励所占比例',
  `SETTLE_INVITER_AWARD` decimal(32,2) DEFAULT '0.00' COMMENT '已结算奖励',
  `AGENT_LEVEL_ID` int(11) DEFAULT NULL COMMENT '代理人等级ID',
  `SETTLE_STATUS` int(11) NOT NULL DEFAULT '1' COMMENT '结算状态 1未结算2部分结算3结算完成',
  `FREEZE_STATUS` int(11) DEFAULT NULL COMMENT '是否冻结 1冻结2正常',
  `AUTO_UNFREEZE_TIME` varchar(20) DEFAULT NULL COMMENT '自动解冻时间 yyyy-MM-dd HH:mm:ss',
  `REMARK` varchar(32) DEFAULT NULL COMMENT '备注',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`COMMISSION_ID`),
  UNIQUE KEY `INDEX_SERNO` (`SERNO`),
  UNIQUE KEY `INDEX_POLICY_NO` (`POLICY_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='佣金收入明细表 ';


CREATE TABLE `t_account_trade_flow` (
  `FLOW_ID` varchar(32) NOT NULL COMMENT '流水号 生成规则:TF+yyyyMMddHHmmssSSS+3位数字随机码',
  `BATCH_ID` varchar(32) DEFAULT NULL COMMENT '批次号 生成规则:BA+yyyyMMddHHmmssSSS+3位数字随机码',
  `ACCOUNT_ID` int(11) DEFAULT NULL COMMENT '资金账号ID',
  `COMMISSION_ID` varchar(32) DEFAULT NULL COMMENT '佣金明细ID',
  `WITHDRAWAL_TYPE` int(11) NOT NULL COMMENT '资金类型 1佣金2红包3邀请人奖励',
  `TRADE_TYPE` int(11) NOT NULL COMMENT '交易动作类型 1提现2冻结3转入',
  `TRADE_AMOUNT` decimal(32,2) NOT NULL DEFAULT '0.00' COMMENT '交易金额',
  `TRADE_DESC` varchar(512) DEFAULT NULL COMMENT '交易说明',
  `BANK_PK_ID` varchar(40) DEFAULT NULL COMMENT '提现银行账户',
  `TRADE_STATUS` int(11) DEFAULT NULL COMMENT '交易状态 1成功2失败3支付中',
  `REMARK` varchar(512) DEFAULT NULL COMMENT '备注',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '交易时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`FLOW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='资金账户交易流水表 ';

CREATE TABLE `t_agent_answer` (
  `ANSWER_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `EXAM_NUMBER` int(11) DEFAULT NULL COMMENT '考试序号',
  `APPLY_ID` varchar(20) NOT NULL COMMENT '代理人申请流水号',
  `QUESTION_ID` int(11) NOT NULL COMMENT '题目编号',
  `AGENT_ANSWER` varchar(32) NOT NULL COMMENT '答案',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ANSWER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=999811758 DEFAULT CHARSET=utf8 COMMENT='代理人考试结果 ';

CREATE TABLE `t_agent_approve_record` (
  `APPROVE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `APPLY_ID` varchar(20) NOT NULL COMMENT '申请流水号',
  `CURRENT_APPROVE_STEP` int(11) NOT NULL COMMENT '审批环节 1申请2自动审批3人工审批4复核5签署合同6上报监管7结束',
  `APPROVE_RESULT` int(11) DEFAULT NULL COMMENT '审批结果 1进行中2否决3通过4结束',
  `APPROVE_OPINION` varchar(512) DEFAULT NULL COMMENT '处理意见',
  `APPROVE_ORG` varchar(32) DEFAULT NULL COMMENT '操作机构',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '接收时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '操作人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  PRIMARY KEY (`APPROVE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1659 DEFAULT CHARSET=utf8 COMMENT='代理人注册审核记录表 ';

CREATE TABLE `t_agent_bank_card` (
  `BANK_ID` varchar(40) NOT NULL COMMENT '主键 UUID',
  `APPLY_ID` varchar(20) NOT NULL COMMENT '代理人流水号',
  `ACCOUNT_NAME` varchar(40) NOT NULL COMMENT '账号名',
  `ACCOUNT_NUMBER` varchar(40) NOT NULL COMMENT '卡号',
  `BANK_CODE` varchar(10) DEFAULT NULL COMMENT '银行编码',
  `BANK_NAME` varchar(40) DEFAULT NULL COMMENT '银行名称',
  `BANK_BRANCH_NAME` varchar(128) DEFAULT NULL COMMENT '支行名称',
  `BANK_BRANCH_CODE` varchar(32) DEFAULT NULL COMMENT '支行编码',
  `BANK_CITY_CODE` varchar(10) DEFAULT NULL COMMENT '开户行市编码',
  `BANK_CITY_NAME` varchar(40) DEFAULT NULL COMMENT '开户行市名称',
  `BANK_PRO_CODE` varchar(32) DEFAULT NULL COMMENT '开户行省编码',
  `BANK_PRO_NAME` varchar(32) DEFAULT NULL COMMENT '开户行省名称',
  `BIND_PHONE` varchar(20) DEFAULT NULL COMMENT '绑定手机号',
  `BIND_FLAG` int(11) DEFAULT NULL COMMENT '销管绑定标志 1绑定销管2未绑定销管',
  `REMARK` varchar(512) DEFAULT NULL COMMENT '备注',
  `STATUS` int(11) NOT NULL DEFAULT '1' COMMENT '状态 1有效2无效',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`BANK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户银行账户信息表 ';


CREATE TABLE `t_agent_certificate` (
  `CERT_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `APPLY_ID` varchar(20) NOT NULL COMMENT '申请流水号',
  `CERT_NUMBER` varchar(64) NOT NULL COMMENT '证件号',
  `CERT_TYPE` int(11) NOT NULL COMMENT '证件类型 1身份证人像面2身份证国徽面3毕业证4学位证5执业证书6半身照',
  `OCR_CONTENT` varchar(3072) DEFAULT NULL COMMENT '证件OCR识别内容 json格式文本存储',
  `UPLOAD_ADDR` varchar(1024) DEFAULT NULL COMMENT '影像平台地址',
  `BEGIN_DATE` varchar(32) DEFAULT NULL COMMENT '证件有效期开始 格式:YYYY-MM-DD',
  `END_DATE` varchar(32) DEFAULT NULL COMMENT '证件有效期结束 格式:YYYY-MM-DD',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`CERT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=999040840 DEFAULT CHARSET=utf8 COMMENT='代理人证件信息表 用户证件信息表';


CREATE TABLE `t_agent_level_info` (
  `AGENT_LEVEL_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '代理人等级ID',
  `AGENT_LEVEL` int(11) NOT NULL COMMENT '代理人等级 1信代新人2信代专员3信代经理4高级信代经理5信代专家',
  `AGENT_LEVEL_NAME` varchar(32) NOT NULL COMMENT '等级称号',
  `MIN_PREMIUM` decimal(32,4) NOT NULL DEFAULT '0.0000' COMMENT '等级标准(保费收入) 单位:元',
  `COMMISSION_RATIO` decimal(32,2) NOT NULL DEFAULT '0.00' COMMENT '等级返佣比例 百分制',
  `AGENT_CASE_ID` varchar(32) NOT NULL COMMENT '方案ID',
  `AGENT_CASE_NAME` varchar(32) NOT NULL COMMENT '方案名称',
  `EFFECT_DATE` varchar(10) NOT NULL COMMENT '方案生效时间 YYYY-MM-DD',
  `DEAD_DATE` varchar(10) NOT NULL COMMENT '方案截止时间 YYYY-MM-DD',
  `AGENCY_AREA_CODE` varchar(20) NOT NULL COMMENT '适用范围地区编码',
  `INVITATION_AWARD` decimal(32,2) NOT NULL DEFAULT '0.00' COMMENT '邀请奖励 百分制',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`AGENT_LEVEL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=147 DEFAULT CHARSET=utf8 COMMENT='代理人等级信息 ';

CREATE TABLE `t_agent_question` (
  `QUESTION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `QUESTION_NUMBER` varchar(10) NOT NULL COMMENT '题库序号',
  `QUESTION_TYPE` int(11) NOT NULL COMMENT '题目类型 1单选2多选',
  `QUESTION_CONTENT` varchar(3072) NOT NULL COMMENT '题目内容 题目内容，json格式',
  `WEIGHT` int(11) NOT NULL COMMENT '权重 越小越靠前',
  `ANSWERS` varchar(32) NOT NULL COMMENT '参考答案',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`QUESTION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8 COMMENT='代理人考试题库 ';

CREATE TABLE `t_agent_register` (
  `APPLY_ID` varchar(20) NOT NULL COMMENT '申请流水号 SG+YYYYMMDD+申请用户ID+2位随机数 示例:SG2020011710000088',
  `USER_NAME` varchar(32) DEFAULT NULL COMMENT '用户姓名',
  `ID_NUMBER` varchar(32) DEFAULT NULL COMMENT '身份证号',
  `EMAIL` varchar(64) DEFAULT NULL COMMENT '绑定邮箱',
  `ETHNIC` varchar(32) DEFAULT NULL COMMENT '民族',
  `POLITICS` varchar(32) DEFAULT NULL COMMENT '政治面貌',
  `EDUCATION` varchar(32) DEFAULT NULL COMMENT '学历',
  `INDUSTRY` varchar(32) DEFAULT NULL COMMENT '行业',
  `AGENCY_AREA_NAME` varchar(32) DEFAULT NULL COMMENT '代理区域名称',
  `AGENCY_AREA_CODE` varchar(32) DEFAULT NULL COMMENT '代理区域编码',
  `BELONG_ORG_NAME` varchar(32) DEFAULT NULL COMMENT '归属机构名称',
  `BELONG_ORG_CODE` varchar(32) DEFAULT NULL COMMENT '归属机构编码',
  `MANAGER_NAME` varchar(32) DEFAULT NULL COMMENT '客户经理名称',
  `MANAGER_ID` varchar(32) DEFAULT NULL COMMENT '客户经理编码',
  `MANAGER_PHONE` varchar(32) DEFAULT NULL COMMENT '客户经理手机',
  `SCORE` int(11) DEFAULT NULL COMMENT '考试分数',
  `APPLY_STATUS` int(11) DEFAULT NULL COMMENT '申请状态 1申请中2自动审批中3人工审批中4合同审批中5合同签署中6信息报备中7申请成功8申请失败9申请超时失效',
  `APPLY_STEP` int(11) DEFAULT NULL COMMENT '当前申请步骤 1未申请2完成实名认证3执业信息保存完成4执业考试完成5人脸识别完成6征信授权书签署完成',
  `PDF_URL` varchar(1024) DEFAULT NULL COMMENT '合同文件浏览地址',
  `SIG_URL` varchar(1024) DEFAULT NULL COMMENT '合同签名短连接',
  `CONFER_CODE` varchar(128) DEFAULT NULL COMMENT '协议代码',
  `CONTRACT_CODE` varchar(128) DEFAULT NULL COMMENT '合同编号',
  `CONFER_TYPE` int(11) DEFAULT NULL COMMENT '协议类型 1补充协议2全量协议',
  `EXIST_AGENT` int(11) DEFAULT NULL COMMENT '申请时是否为公司代理人 1是2否',
  `AGENT_TYPE` int(11) DEFAULT NULL COMMENT '申请代理人类型 1--普通个代    2--独立个代   3--专属个代',
  `CREATED_TIME` datetime NOT NULL COMMENT '申请时间',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`APPLY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='代理人注册信息表 ';

CREATE TABLE `t_commision_detail_correct` (
  `CORRECT_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `SERNO` varchar(32) DEFAULT NULL COMMENT '业务流水号',
  `LIST_SERNO` varchar(32) DEFAULT NULL COMMENT '保单号',
  `COMMISION_ID` varchar(32) DEFAULT NULL COMMENT '佣金明细流水号',
  `OLD_PREMIUM` decimal(32,2) DEFAULT '0.00' COMMENT '批改前保费收入',
  `NEW_PREMIUM` decimal(32,2) DEFAULT '0.00' COMMENT '批改后保费收入',
  `OLD_POUNDAGE` decimal(32,2) DEFAULT '0.00' COMMENT '批改前合计手续费',
  `NEW_POUNDAGE` decimal(32,2) DEFAULT '0.00' COMMENT '批改后合计手续费',
  `CHANGE_POUNDAGE` decimal(32,2) DEFAULT '0.00' COMMENT '合计手续费变动值',
  `OLD_COMMISION` decimal(32,2) DEFAULT '0.00' COMMENT '批改前代理人佣金',
  `NEW_COMMISION` decimal(32,2) DEFAULT '0.00' COMMENT '批改后代理人佣金',
  `CHANGE_COMMISION` decimal(32,2) DEFAULT '0.00' COMMENT '佣金变动值',
  `PMR_SERNO` varchar(32) DEFAULT NULL COMMENT '信保批改流水号',
  `ENDORSEMENT_SERNO` varchar(32) DEFAULT NULL COMMENT '核心批单号',
  `ENDERSERNO` varchar(32) DEFAULT NULL COMMENT '批单序号',
  `RESULT` int(11) DEFAULT NULL COMMENT '批改结果 1批改中2批改成功3批改失败',
  `MOD_TYPE` int(11) DEFAULT NULL COMMENT '批改类型 1手续费批增2手续费批减',
  `SOURCE` int(11) DEFAULT NULL COMMENT '批改来源 1退保2批改3注销4重计提',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`CORRECT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=91 DEFAULT CHARSET=utf8 COMMENT='手续费批改记录表 ';

CREATE TABLE `t_commision_settle_plan` (
  `PLAN_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '计划主键ID',
  `COMMISSION_ID` varchar(32) NOT NULL COMMENT '佣金流水号',
  `SERNO` varchar(32) NOT NULL COMMENT '业务流水号',
  `PERIOD` int(11) NOT NULL COMMENT '结算阶段(期次)',
  `DUE_DATE` varchar(10) NOT NULL COMMENT '应付日期 YYYY-MM-DD',
  `DUE_AMOUNT` decimal(32,2) NOT NULL DEFAULT '0.00' COMMENT '应付金额',
  `REAL_DATE` varchar(30) DEFAULT NULL COMMENT '实付日期 YYYY-MM-DD HH:MM:SS',
  `REAL_AMOUNT` decimal(32,2) DEFAULT '0.00' COMMENT '实付金额',
  `PAY_STATUS` int(11) NOT NULL COMMENT '支付状态 1.待支付2.支付中3.支付成功4.支付失败',
  `BATCH_ID` varchar(32) DEFAULT NULL COMMENT '结算批次号 同资金流水表批次号',
  `ENDORSEQNO` varchar(10) NOT NULL COMMENT '批单序号 初始000,批改一次增1,如001,002',
  `RISK_CODE` varchar(10) NOT NULL COMMENT '险种代码',
  `CHANGE_AMOUNT` decimal(32,2) DEFAULT '0.00' COMMENT '金额变动量',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`PLAN_ID`,`CREATED_BY`,`CREATED_TIME`)
) ENGINE=InnoDB AUTO_INCREMENT=10787 DEFAULT CHARSET=utf8 COMMENT='佣金结算计划表 ';

CREATE TABLE `t_commission_detail` (
  `COMMISSION_ID` varchar(32) NOT NULL COMMENT '主键 生成规则:DF+yyyyMMddHHmmssSSS+3位数字随机码',
  `SERNO` varchar(40) NOT NULL COMMENT '业务流水号',
  `POLICY_NO` varchar(32) DEFAULT NULL COMMENT '保单号',
  `CUS_NAME` varchar(32) DEFAULT NULL COMMENT '客户姓名',
  `CUS_PHONE` varchar(32) DEFAULT NULL COMMENT '客户手机号',
  `USER_ID` varchar(32) DEFAULT NULL COMMENT '代理人ID',
  `USER_NAME` varchar(32) DEFAULT NULL COMMENT '代理人姓名',
  `USER_PHONE` varchar(32) DEFAULT NULL COMMENT '代理人手机号',
  `INVITER_USER_ID` varchar(32) DEFAULT NULL COMMENT '邀请人ID',
  `INVITER_USER_NAME` varchar(32) DEFAULT NULL COMMENT '邀请人姓名',
  `INVITER_USER_PHONE` varchar(32) DEFAULT NULL COMMENT '邀请人手机号',
  `CUS_MAMAGER_ID` varchar(32) DEFAULT NULL COMMENT '客户经理ID',
  `CUS_MAMAGER_NAME` varchar(32) DEFAULT NULL COMMENT '客户经理姓名',
  `DEPT_CODE` varchar(32) DEFAULT NULL COMMENT '所属分部编码',
  `DEPT_NAME` varchar(128) DEFAULT NULL COMMENT '所属分部名称',
  `LOAN_DATE` varchar(20) DEFAULT NULL COMMENT '放款时间 yyyy-MM-dd HH:mm:ss',
  `LOAN_AMOUNT` decimal(32,2) DEFAULT '0.00' COMMENT '放款金额',
  `POLICY_DATE` varchar(20) DEFAULT NULL COMMENT '出单时间 yyyy-MM-dd HH:mm:ss',
  `APPROVE_RESULT` varchar(10) DEFAULT NULL COMMENT '预审结果',
  `APPROVE_DATE` varchar(20) DEFAULT NULL COMMENT '预审时间 yyyy-MM-dd HH:mm:ss',
  `PREMIUM_AMOUNT` decimal(32,2) DEFAULT '0.00' COMMENT '保费收入',
  `PURE_PREMIUM_AMOUNT` decimal(32,2) DEFAULT '0.00' COMMENT '保费收入(不含税)',
  `APPLY_STATUS` varchar(10) DEFAULT NULL COMMENT '申请状态',
  `TOTAL_POUNDAGE` decimal(32,2) DEFAULT '0.00' COMMENT '合计手续费',
  `POUNDAGE_RATE` decimal(32,4) DEFAULT '0.0000' COMMENT '手续费所占比例',
  `AGENT_COMMISSION` decimal(32,2) DEFAULT '0.00' COMMENT '代理人佣金',
  `COMMISSION_RATE` decimal(32,4) DEFAULT '0.0000' COMMENT '佣金所占比例',
  `SETTLE_COMMISSION` decimal(32,2) DEFAULT '0.00' COMMENT '已结算佣金',
  `INVITER_AWARD` decimal(32,2) DEFAULT '0.00' COMMENT '邀请人奖励',
  `AWARD_RATE` decimal(32,4) DEFAULT '0.0000' COMMENT '奖励所占比例',
  `SETTLE_INVITER_AWARD` decimal(32,2) DEFAULT '0.00' COMMENT '已结算奖励',
  `AGENT_LEVEL_ID` int(11) DEFAULT NULL COMMENT '代理人等级ID',
  `SETTLE_STATUS` int(11) NOT NULL DEFAULT '1' COMMENT '结算状态 1未结算2部分结算3结算完成',
  `FREEZE_STATUS` int(11) DEFAULT NULL COMMENT '是否冻结 1冻结2正常',
  `AUTO_UNFREEZE_TIME` varchar(20) DEFAULT NULL COMMENT '自动解冻时间 yyyy-MM-dd HH:mm:ss',
  `REMARK` varchar(32) DEFAULT NULL COMMENT '备注',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`COMMISSION_ID`),
  UNIQUE KEY `INDEX_SERNO` (`SERNO`),
  UNIQUE KEY `INDEX_POLICY_NO` (`POLICY_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='佣金收入明细表 ';

CREATE TABLE `t_function_area_info` (
  `AREA_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `AREA_TYPE` int(11) NOT NULL COMMENT '功能区类型 1隐私政策2用户协议3联系我们4关于我们',
  `AREA_CONTENT` longtext NOT NULL COMMENT '功能区内容',
  `AREA_STATUS` int(11) NOT NULL DEFAULT '1' COMMENT '状态 1有效2无效',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`AREA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=996600739 DEFAULT CHARSET=utf8 COMMENT='功能区信息表';

CREATE TABLE `t_help_info` (
  `HELP_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `QUESTION` varchar(1024) DEFAULT NULL COMMENT '问题',
  `ANSWER` varchar(3072) DEFAULT NULL COMMENT '答案',
  `STATUS` int(11) DEFAULT '1' COMMENT '状态 1有效2无效',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`HELP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='问题记录信息表 ';

CREATE TABLE `t_notice_info` (
  `NOTICE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NOTICE_TITLE` varchar(1024) DEFAULT NULL COMMENT '消息标题',
  `NOTICE_TYPE` int(11) DEFAULT NULL COMMENT '消息类型 1公告2私信',
  `NOTICE_TAG` varchar(32) DEFAULT NULL COMMENT '标签',
  `NOTICE_URL` varchar(128) DEFAULT NULL COMMENT '链接',
  `REMARK` varchar(512) DEFAULT NULL COMMENT '备注',
  `NOTICE_OBJECT` text COMMENT '推送对象',
  `STATUS` int(11) NOT NULL DEFAULT '1' COMMENT '状态 1上架2下架',
  `PUSH_TIME` datetime NOT NULL COMMENT '发布时间',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`NOTICE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=182 DEFAULT CHARSET=utf8 COMMENT='推送消息记录表 ';

CREATE TABLE `t_notice_record` (
  `RECORD_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID` int(11) NOT NULL COMMENT '用户ID',
  `NOTICE_ID` int(11) NOT NULL COMMENT '消息ID',
  `CREATED_BY` varchar(32) DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`RECORD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='推送记录表 ';

CREATE TABLE `t_out_req_log` (
  `LOG_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `SERNO` varchar(32) DEFAULT NULL COMMENT '业务流水号',
  `LOG_TYPE` varchar(32) DEFAULT NULL COMMENT '业务日志类型',
  `INNER_PARAM` text COMMENT '内部请求参数',
  `REQ_PARAM` text COMMENT '外部请求参数',
  `RSP_PARAM` text COMMENT '外部返回参数',
  `STATUS` int(11) DEFAULT NULL COMMENT '请求状态 1请求完成2请求异常',
  `CREATED_BY` varchar(32) DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4088 DEFAULT CHARSET=utf8 COMMENT='外部交互日志表 ';

CREATE TABLE `t_product_area_config` (
  `CREATED_BY` varchar(32) DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='待定--产品可用区域配置信息表 ';

CREATE TABLE `t_product_base_info` (
  `PRODUCT_ID` varchar(40) NOT NULL COMMENT '主键 UUID',
  `PRODUCT_CODE` varchar(10) NOT NULL COMMENT '产品代码',
  `PRODUCT_NAME` varchar(32) NOT NULL COMMENT '产品名称',
  `VALID_STATUS` int(11) NOT NULL DEFAULT '1' COMMENT '产品有效状态 1上架2下架',
  `ORDER_WEIGHT` int(11) NOT NULL COMMENT '排序权重 越小越靠前',
  `PRODUCT_DESC` varchar(128) DEFAULT NULL COMMENT '产品描述',
  `PRODUCT_FEATURES` varchar(128) DEFAULT NULL COMMENT '产品特点',
  `IMG_URL` varchar(512) DEFAULT NULL COMMENT '产品图标影像地址',
  `POSTER_URL` varchar(512) DEFAULT NULL COMMENT '产品营销海报地址',
  `REMARK` varchar(512) DEFAULT NULL COMMENT '备注',
  `MIN_LOAN_QUOTA` decimal(32,2) DEFAULT '50000.00' COMMENT '最小贷款额度',
  `MAX_LOAN_QUOTA` decimal(32,2) DEFAULT '300000.00' COMMENT '最大贷款额度',
  `MIN_LOAN_MONTHS` decimal(32,2) DEFAULT '12.00' COMMENT '最小贷款月数',
  `MAX_LOAN_MONTHS` decimal(32,2) DEFAULT '36.00' COMMENT '最大贷款月数',
  `LAUNCH_CITY_CODE` varchar(1024) DEFAULT NULL COMMENT '投放城市编码',
  `LAUNCH_CITY_NAME` varchar(1024) DEFAULT NULL COMMENT '投放城市名称',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='产品基础信息表 ';

CREATE TABLE `t_product_module_config` (
  `MODULE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `PRODUCT_PK_ID` varchar(32) NOT NULL COMMENT '产品主键',
  `PRODUCT_CODE` varchar(10) NOT NULL COMMENT '产品编码',
  `MODULE_TYPE` int(11) NOT NULL COMMENT '模块类型 1图文详情2常见问题',
  `MODULE_TITLE` varchar(128) NOT NULL COMMENT '模块标题',
  `MODULE_CONTENT` longtext NOT NULL COMMENT '模块内容',
  `MODULE_LINK` varchar(512) DEFAULT NULL COMMENT '详情链接',
  `VALID_STATUS` int(11) NOT NULL DEFAULT '1' COMMENT '有效状态 1有效2无效',
  `SOURCE_PLAT` int(11) DEFAULT NULL COMMENT '来源平台 1.个人代理',
  `REMARK` varchar(512) DEFAULT NULL COMMENT '备注',
  `WEIGHT` int(11) DEFAULT NULL COMMENT '权重 权重越小越靠前',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`MODULE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8 COMMENT='产品模块配置信息表 ';

CREATE TABLE `t_publish_info` (
  `PUBLISH_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ARTICLE_NO` varchar(32) DEFAULT NULL COMMENT '文章编号',
  `ARTICLE_TITLE` varchar(40) DEFAULT NULL COMMENT '文章标题',
  `ARTICLE_TYPE` int(11) DEFAULT NULL COMMENT '文章类型 1信保大学文章2咨询3其它',
  `ARTICLE_CONTENT` text COMMENT '文章内容',
  `ARTICLE_AUTHOR` varchar(32) DEFAULT NULL COMMENT '文章作者',
  `PUBLISH_TIME` datetime DEFAULT NULL COMMENT '发布时间',
  `ARTICLE_LINK` varchar(128) DEFAULT NULL COMMENT '文章链接',
  `STATUS` int(11) DEFAULT '1' COMMENT '有效状态 1有效2无效',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`PUBLISH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='图文发布详情 ';

CREATE TABLE `t_user_base_info` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '用户ID 主键',
  `PHONE_NUMBER` varchar(32) NOT NULL COMMENT '用户手机号',
  `PASSWORD` varchar(32) NOT NULL COMMENT '登录密码',
  `SALT` int(11) NOT NULL COMMENT '盐值 100到999的随机整数',
  `USER_TYPE` int(11) NOT NULL DEFAULT '1' COMMENT '用户类型 1普通用户2代理人  对应字典表key值:AGENT_USER_TYPE',
  `AGENT_LEVEL_ID` int(11) DEFAULT NULL COMMENT '代理人等级ID',
  `AGENT_LEVEL` int(11) DEFAULT NULL COMMENT '代理人等级',
  `USER_STATUS` int(11) NOT NULL DEFAULT '1' COMMENT '账号状态 1正常2代理申请审核3冻结4永久封号 对应字典表key值:AGENT_USER_STATUS',
  `PHOTO_ADDR` varchar(1024) DEFAULT NULL COMMENT '用户头像地址',
  `INVITER_TYPE` int(11) DEFAULT NULL COMMENT '邀请人类型 1内部员工2代理人 字典表key值:AGENT_INVITER_TYPE',
  `INVITER_USER_ID` varchar(20) DEFAULT NULL COMMENT '邀请人ID',
  `INVITER_NAME` varchar(32) DEFAULT NULL COMMENT '邀请人姓名',
  `OPEN_ID` varchar(64) DEFAULT NULL COMMENT '绑定微信OPENID',
  `WECHAT_NICK_NAME` varchar(64) DEFAULT NULL COMMENT '绑定微信名',
  `APPLY_ID` varchar(20) DEFAULT NULL COMMENT '代理人申请流水号',
  `PRACTICE_NUMBER` varchar(40) DEFAULT NULL COMMENT '代理人在销管执业证号',
  `SALE_AGENT_CODE` varchar(32) DEFAULT NULL COMMENT '代理人在销管系统编码',
  `LATEST_LOGIN_TIME` datetime DEFAULT NULL COMMENT '最近登录时间',
  `LATEST_LOGIN_CITY` varchar(32) DEFAULT NULL COMMENT '最近登录地点',
  `REGISTRATION_ID` varchar(32) DEFAULT NULL COMMENT '当前登录设备号',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `INDEX_PHONE` (`PHONE_NUMBER`),
  UNIQUE KEY `INDEX_OPEN_ID` (`OPEN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=89386194 DEFAULT CHARSET=utf8 COMMENT='用户基本信息表';

CREATE TABLE `t_user_login_log` (
  `LOG_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID` int(11) NOT NULL COMMENT '用户ID',
  `LOGIN_TYPE` int(11) NOT NULL COMMENT '登录类型 1短信登录2账号登录3微信登录4退出登录',
  `REGISTRATION_ID` varchar(32) DEFAULT NULL COMMENT '登录设备号',
  `LOGIN_CITY` varchar(32) DEFAULT NULL COMMENT '登录地点',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NOT NULL COMMENT '登录时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5460 DEFAULT CHARSET=utf8 COMMENT='用户登录日志表 ';

CREATE TABLE `t_user_status_change` (
  `CHANGE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID` int(11) NOT NULL COMMENT '被变更人ID',
  `STATUS_BEFORE` int(11) NOT NULL COMMENT '变更前状态',
  `STATUS_AFTER` int(11) NOT NULL COMMENT '变更后状态',
  `CHANGE_REASON` varchar(1024) NOT NULL COMMENT '变更原因',
  `CREATED_BY` varchar(32) NOT NULL COMMENT '变更操作人',
  `CREATED_TIME` datetime NOT NULL COMMENT '变更时间',
  `UPDATED_BY` varchar(32) DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`CHANGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户状态变更记录表';